import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { ChatComponent } from "../components/ChatComponent/ChatComponent";
import {
    ProductContext,
    ProductContextProvider,
} from "../components/context/ProductContextProvider";
import { UserContextProvider } from "../components/context/UserContextProvider";
import { NavbarComponent } from "../components/NavbarComponent/NavbarComponent";
import { ProductListContainer } from "../components/ProductListContainer/ProductListContainer";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <UserContextProvider>
            <ProductContextProvider>
                <div className={styles.container}>
                    <Head>
                        <title>Create Next App</title>
                        <meta
                            name="description"
                            content="Generated by create next app"
                        />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <NavbarComponent />
                    <ProductListContainer />
                    <ChatComponent />
                </div>{" "}
            </ProductContextProvider>
        </UserContextProvider>
    );
};

export default Home;
