import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import {
    ProductContext,
    ProductContextProvider,
} from "../../components/context/ProductContextProvider";
import { UserContextProvider } from "../../components/context/UserContextProvider";
import { NavbarComponent } from "../../components/NavbarComponent/NavbarComponent";
import { ProductDetailContainer } from "../../components/ProductDetailContainer/ProductDetailContainer";
import { ProductListContainer } from "../../components/ProductListContainer/ProductListContainer";

import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
    const [id, setId] = useState<string>("");
    const router = useRouter();

    useEffect(() => {
        console.log(router.query.id);

        if (router.query.id) {
            setId(router.query.id as string);
        }
    }, [router.query]);

    useEffect(() => {}, [id]);

    return (
        <UserContextProvider>
            <ProductContextProvider>
                <div className={styles.container}>
                    <Head>
                        <title>Create Next App</title>
                        <meta
                            name="description"
                            content="Generated by create next app"
                        />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <NavbarComponent />
                    <ProductDetailContainer id={id} />
                    <button
                        onClick={() => {
                            router.push("/");
                        }}
                    >
                        Al Inicio
                    </button>
                </div>{" "}
            </ProductContextProvider>
        </UserContextProvider>
    );
};

export default Home;
